/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ParticipantesRouteImport } from './routes/participantes'
import { Route as JuiciosRouteImport } from './routes/juicios'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as AgendamientoRouteImport } from './routes/agendamiento'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParticipantesNuevoRouteImport } from './routes/participantes.nuevo'
import { Route as JuiciosNuevoRouteImport } from './routes/juicios.nuevo'
import { Route as JuiciosIdRouteImport } from './routes/juicios.$id'
import { Route as ParticipantesIdEditarRouteImport } from './routes/participantes.$id.editar'

const ParticipantesRoute = ParticipantesRouteImport.update({
  id: '/participantes',
  path: '/participantes',
  getParentRoute: () => rootRouteImport,
} as any)
const JuiciosRoute = JuiciosRouteImport.update({
  id: '/juicios',
  path: '/juicios',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendamientoRoute = AgendamientoRouteImport.update({
  id: '/agendamiento',
  path: '/agendamiento',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantesNuevoRoute = ParticipantesNuevoRouteImport.update({
  id: '/nuevo',
  path: '/nuevo',
  getParentRoute: () => ParticipantesRoute,
} as any)
const JuiciosNuevoRoute = JuiciosNuevoRouteImport.update({
  id: '/nuevo',
  path: '/nuevo',
  getParentRoute: () => JuiciosRoute,
} as any)
const JuiciosIdRoute = JuiciosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => JuiciosRoute,
} as any)
const ParticipantesIdEditarRoute = ParticipantesIdEditarRouteImport.update({
  id: '/$id/editar',
  path: '/$id/editar',
  getParentRoute: () => ParticipantesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendamiento': typeof AgendamientoRoute
  '/auditoria': typeof AuditoriaRoute
  '/juicios': typeof JuiciosRouteWithChildren
  '/participantes': typeof ParticipantesRouteWithChildren
  '/juicios/$id': typeof JuiciosIdRoute
  '/juicios/nuevo': typeof JuiciosNuevoRoute
  '/participantes/nuevo': typeof ParticipantesNuevoRoute
  '/participantes/$id/editar': typeof ParticipantesIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendamiento': typeof AgendamientoRoute
  '/auditoria': typeof AuditoriaRoute
  '/juicios': typeof JuiciosRouteWithChildren
  '/participantes': typeof ParticipantesRouteWithChildren
  '/juicios/$id': typeof JuiciosIdRoute
  '/juicios/nuevo': typeof JuiciosNuevoRoute
  '/participantes/nuevo': typeof ParticipantesNuevoRoute
  '/participantes/$id/editar': typeof ParticipantesIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendamiento': typeof AgendamientoRoute
  '/auditoria': typeof AuditoriaRoute
  '/juicios': typeof JuiciosRouteWithChildren
  '/participantes': typeof ParticipantesRouteWithChildren
  '/juicios/$id': typeof JuiciosIdRoute
  '/juicios/nuevo': typeof JuiciosNuevoRoute
  '/participantes/nuevo': typeof ParticipantesNuevoRoute
  '/participantes/$id/editar': typeof ParticipantesIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendamiento'
    | '/auditoria'
    | '/juicios'
    | '/participantes'
    | '/juicios/$id'
    | '/juicios/nuevo'
    | '/participantes/nuevo'
    | '/participantes/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendamiento'
    | '/auditoria'
    | '/juicios'
    | '/participantes'
    | '/juicios/$id'
    | '/juicios/nuevo'
    | '/participantes/nuevo'
    | '/participantes/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/agendamiento'
    | '/auditoria'
    | '/juicios'
    | '/participantes'
    | '/juicios/$id'
    | '/juicios/nuevo'
    | '/participantes/nuevo'
    | '/participantes/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendamientoRoute: typeof AgendamientoRoute
  AuditoriaRoute: typeof AuditoriaRoute
  JuiciosRoute: typeof JuiciosRouteWithChildren
  ParticipantesRoute: typeof ParticipantesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/participantes': {
      id: '/participantes'
      path: '/participantes'
      fullPath: '/participantes'
      preLoaderRoute: typeof ParticipantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juicios': {
      id: '/juicios'
      path: '/juicios'
      fullPath: '/juicios'
      preLoaderRoute: typeof JuiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendamiento': {
      id: '/agendamiento'
      path: '/agendamiento'
      fullPath: '/agendamiento'
      preLoaderRoute: typeof AgendamientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participantes/nuevo': {
      id: '/participantes/nuevo'
      path: '/nuevo'
      fullPath: '/participantes/nuevo'
      preLoaderRoute: typeof ParticipantesNuevoRouteImport
      parentRoute: typeof ParticipantesRoute
    }
    '/juicios/nuevo': {
      id: '/juicios/nuevo'
      path: '/nuevo'
      fullPath: '/juicios/nuevo'
      preLoaderRoute: typeof JuiciosNuevoRouteImport
      parentRoute: typeof JuiciosRoute
    }
    '/juicios/$id': {
      id: '/juicios/$id'
      path: '/$id'
      fullPath: '/juicios/$id'
      preLoaderRoute: typeof JuiciosIdRouteImport
      parentRoute: typeof JuiciosRoute
    }
    '/participantes/$id/editar': {
      id: '/participantes/$id/editar'
      path: '/$id/editar'
      fullPath: '/participantes/$id/editar'
      preLoaderRoute: typeof ParticipantesIdEditarRouteImport
      parentRoute: typeof ParticipantesRoute
    }
  }
}

interface JuiciosRouteChildren {
  JuiciosIdRoute: typeof JuiciosIdRoute
  JuiciosNuevoRoute: typeof JuiciosNuevoRoute
}

const JuiciosRouteChildren: JuiciosRouteChildren = {
  JuiciosIdRoute: JuiciosIdRoute,
  JuiciosNuevoRoute: JuiciosNuevoRoute,
}

const JuiciosRouteWithChildren =
  JuiciosRoute._addFileChildren(JuiciosRouteChildren)

interface ParticipantesRouteChildren {
  ParticipantesNuevoRoute: typeof ParticipantesNuevoRoute
  ParticipantesIdEditarRoute: typeof ParticipantesIdEditarRoute
}

const ParticipantesRouteChildren: ParticipantesRouteChildren = {
  ParticipantesNuevoRoute: ParticipantesNuevoRoute,
  ParticipantesIdEditarRoute: ParticipantesIdEditarRoute,
}

const ParticipantesRouteWithChildren = ParticipantesRoute._addFileChildren(
  ParticipantesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendamientoRoute: AgendamientoRoute,
  AuditoriaRoute: AuditoriaRoute,
  JuiciosRoute: JuiciosRouteWithChildren,
  ParticipantesRoute: ParticipantesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
